import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

import { build } from 'esbuild'

const applicationDirectory = resolve(import.meta.dirname, '..')
const outputDirectory = resolve(applicationDirectory, 'miniprogram/generated')

await mkdir(outputDirectory, { recursive: true })
await build({
  banner: {
    js: '/* Generated by pnpm --filter @wx-upload/miniprogram bundle:contracts. */',
  },
  bundle: true,
  charset: 'utf8',
  entryPoints: [resolve(import.meta.dirname, 'contracts-runtime-entry.mjs')],
  format: 'esm',
  legalComments: 'none',
  logLevel: 'info',
  minify: false,
  outfile: resolve(outputDirectory, 'contracts.js'),
  platform: 'neutral',
  sourcemap: false,
  target: 'es2020',
  treeShaking: true,
})
